INSERT INTO artist (id, name, genre) VALUES(1, "D'Angelo", "Neo-Soul");
INSERT INTO artist (id, name, genre) VALUES(2, "Horse Feathers", "Folk");
INSERT INTO artist (id, name, genre) VALUES(3, "Lauryn Hill", "Hip Hop");
INSERT INTO artist (id, name, genre) VALUES(4, "M.I.A.", "Hip Hop");
INSERT INTO artist (id, name, genre) VALUES(5, "Radiohead", "Electronic Rock");
INSERT INTO artist (id, name, genre) VALUES(6, "Santogold", "Alternative Hip Hop");
INSERT INTO artist (id, name, genre) VALUES(7, "TV On The Radio", "Rock");

INSERT INTO albums (id, artist_id, title, year) VALUES(1, 1, "Voodoo", 2000);
INSERT INTO albums (id, artist_id, title, year) VALUES(2, 1, "Brown Sugar", 1995);
INSERT INTO albums (id, artist_id, title, year) VALUES(3, 2, "House with No Home", 2008);
INSERT INTO albums (id, artist_id, title, year) VALUES(4, 3, "The Miseducation Of Lauryn Hill", 1998);
INSERT INTO albums (id, artist_id, title, year) VALUES(5, 4, "Kala", 2007);
INSERT INTO albums (id, artist_id, title, year) VALUES(6, 5, "In Rainbows", 2007);
INSERT INTO albums (id, artist_id, title, year) VALUES(7, 5, "Amnesiac", 2001);
INSERT INTO albums (id, artist_id, title, year) VALUES(8, 6, "Santogold", 2008);
INSERT INTO albums (id, artist_id, title, year) VALUES(9, 7, "Dear Science", 2008);
INSERT INTO albums (id, artist_id, title, year) VALUES(10, 7, "Desperate Youth, Blood Thirsty Babes", 2004);

INSERT INTO songs (id, title, album_id, length, track_no) VALUES(1, "Playa Playa", 1, 426, 1 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(2, "Devil's Pie", 1, 321, 2 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(3, "Left & Right (Featuring Method Man And Redman)", 1, 286, 3 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(4, "The Line", 1, 316, 4 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(5, "Send It On", 1, 356, 5 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(6, "Chicken Grease", 1, 278, 6 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(7, "One Mo'gin", 1, 373, 7 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(8, "The Root", 1, 393, 8 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(9, "Spanish Joint", 1, 344, 9 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(10, "Feel Like Makin' Love", 1, 382, 10 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(11, "Greatdayndamorn'/Booty", 1, 455, 11 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(12, "Untitled (How Does It Feel)", 1, 430, 12 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(13, "Brown Sugar", 2, 263, 1 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(14, "Alright", 2, 313, 2 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(15, "Jonz In My Bonz", 2, 356, 3 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(16, "Me And Those Dreamin' Eyes Of Mine", 2, 286, 4 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(17, "Shit, Damn, Motherfucker", 2, 314, 5 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(18, "Smooth", 2, 259, 6 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(19, "Cruisin'", 2, 384, 7 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(20, "When We Get By", 2, 344, 8 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(21, "Lady", 2, 346, 9 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(22, "Higher", 2, 327, 10 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(23, "Curs in the Weeds", 3, 210, 1 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(24, "Rude to Rile", 3, 209, 2 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(25, "Working Poor", 3, 196, 3 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(26, "Albina", 3, 137, 4 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(27, "A Burden", 3, 211, 5 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(28, "Helen", 3, 260, 6 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(29, "Father (Reprise)", 3, 121, 7 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(30, "Heathen's Kiss", 3, 280, 8 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(31, "Different Gray", 3, 176, 9 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(32, "This Is What", 3, 189, 10 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(33, "Father", 3, 210, 11 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(34, "Intro", 4, 47, 1 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(35, "Lost Ones", 4, 333, 2 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(36, "Ex Factor", 4, 326, 3 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(37, "To Zion", 4, 369, 4 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(38, "Doo Wop (That Thing)", 4, 320, 5 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(39, "Superstar", 4, 297, 6 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(40, "Final Hour", 4, 256, 7 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(41, "When It Hurts So Bad", 4, 342, 8 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(42, "I Used To Love Him", 4, 339, 9 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(43, "Forgive Them Father", 4, 315, 10 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(44, "Every Ghetto Every City", 4, 314, 11 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(45, "Nothing Even Matters", 4, 350, 12 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(46, "Everything Is Everything", 4, 293, 13 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(47, "Miseducation Of Lauryn Hill", 4, 257, 14 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(48, "Can't Take My Eyes Off Of You", 4, 221, 15 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(49, "Tell Him", 4, 280, 16 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(50, "Bamboo Banger", 5, 298, 1 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(51, "Bird Flu", 5, 204, 2 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(52, "Boyz", 5, 207, 3 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(53, "Jimmy", 5, 209, 4 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(54, "Hussel (feat. Afrikan Boy)", 5, 265, 5 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(55, "Mango Pickle Down River (with The Wilcannia Mob)", 5, 233, 6 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(56, "$20", 5, 274, 7 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(57, "Down River", 5, 233, 8 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(58, "The Turn", 5, 232, 9 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(59, "XR2", 5, 260, 10 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(60, "Paper Planes", 5, 204, 11 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(61, "Come Around (feat. Timbaland)", 5, 233, 12 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(62, "15 Step", 6, 237, 1 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(63, "Bodysnatchers", 6, 242, 2 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(64, "Nude", 6, 255, 3 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(65, "Weird Fishes/Arpeggi", 6, 318, 4 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(66, "All I Need", 6, 228, 5 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(67, "Faust Arp", 6, 129, 6 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(68, "Reckoner", 6, 290, 7 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(69, "House Of Cards", 6, 328, 8 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(70, "Jigsaw Falling Into Place", 6, 248, 9 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(71, "Videotape", 6, 279, 10 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(72, "Packt Like Sardines In A Crushd Tin Box", 7, 240, 1 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(73, "Pyramid Song", 7, 288, 2 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(74, "Pulk/Pull Revolving Doors", 7, 247, 3 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(75, "You And Whose Army?", 7, 190, 4 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(76, "I Might Be Wrong", 7, 293, 5 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(77, "Knives Out", 7, 254, 6 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(78, "Morning Bell/Amnesiac", 7, 194, 7 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(79, "Dollars & Cents", 7, 291, 8 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(80, "Hunting Bears", 7, 121, 9 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(81, "Like Spinning Plates", 7, 237, 10 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(82, "Life In A Glass House", 7, 274, 11 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(83, "Anne", 8, 208, 1 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(84, "Creator", 8, 213, 2 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(85, "I'm a Lady", 8, 223, 3 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(86, "LES artistes", 8, 204, 4 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(87, "Lights Out", 8, 192, 5 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(88, "My Superman", 8, 180, 6 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(89, "Say Aha", 8, 215, 7 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(90, "shove It", 8, 226, 8 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(91, "Startruck", 8, 234, 9 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(92, "Unstppable", 8, 212, 10 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(93, "You´ll Find A Way", 8, 180, 11 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(94, "You´ll Find A way(remix)", 8, 192, 12 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(95, "Halfway Home", 9, 331, 1 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(96, "Crying", 9, 250, 2 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(97, "Dancing Choose", 9, 176, 3 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(98, "Stork And Owl", 9, 241, 4 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(99, "Golden Age", 9, 251, 5 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(100, "Family Tree", 9, 333, 6 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(101, "Red Dress", 9, 265, 7 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(102, "Love Dog", 9, 336, 8 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(103, "Shout Me Out", 9, 255, 9 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(104, "DLZ", 9, 228, 10 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(105, "Lover's Day", 9, 355, 11 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(106, "The Wrong Way", 10, 278, 1 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(107, "Staring at the Sun", 10, 206, 2 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(108, "Dreams", 10, 309, 3 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(109, "King Eternal", 10, 267, 4 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(110, "Ambulance", 10, 294, 5 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(111, "Poppy", 10, 367, 6 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(112, "Don't Love You", 10, 331, 7 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(113, "Bomb Yourself", 10, 331, 8 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(114, "Wear You Out", 10, 440, 9 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(115, "You Could Be Love", 10, 436, 10 );
INSERT INTO songs (id, title, album_id, length, track_no) VALUES(116, "Staring at the Sun (Demo)", 10, 377, 11 ););

/*playlist mock data*/
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (1, 'Vagram', 'Fixflex', 'Y-find', 344);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (2, 'Bamity', 'Cardguard', 'Voltsillam', 270);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (3, 'Ronstring', 'Zaam-Dox', 'Veribet', 67);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (4, 'Flowdesk', 'Alpha', 'Sub-Ex', 298);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (5, 'Regrant', 'Stronghold', 'Bamity', 97);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (6, 'Duobam', 'Flexidy', 'Asoka', 141);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (7, 'Tin', 'Duobam', 'Fintone', 177);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (8, 'Y-find', 'Zontrax', 'Voltsillam', 316);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (9, 'Subin', 'Asoka', 'Cardify', 79);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (10, 'Latlux', 'Opela', 'Aerified', 268);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (11, 'Temp', 'Tampflex', 'Bitwolf', 215);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (12, 'Keylex', 'Konklab', 'Bigtax', 228);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (13, 'Keylex', 'Konklab', 'Aerified', 59);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (14, 'Voyatouch', 'Treeflex', 'Kanlam', 333);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (15, 'Span', 'Konklux', 'Home Ing', 52);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (16, 'Trippledex', 'Fix San', 'Bamity', 168);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (17, 'Daltfresh', 'Stringtough', 'Lotlux', 81);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (18, 'Alphazap', 'Redhold', 'Lotstring', 31);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (19, 'Tin', 'Hatity', 'Overhold', 133);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (20, 'Temp', 'Biodex', 'Namfix', 191);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (21, 'Aerified', 'Fintone', 'Greenlam', 318);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (22, 'Konklab', 'Zathin', 'Solarbreeze', 219);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (23, 'Zoolab', 'Opela', 'Lotstring', 228);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (24, 'Y-Solowarm', 'Konklux', 'Job', 312);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (25, 'Zamit', 'Alpha', 'Gembucket', 115);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (26, 'Toughjoyfax', 'Ronstring', 'Greenlam', 108);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (27, 'Biodex', 'Stringtough', 'Quo Lux', 335);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (28, 'Redhold', 'Tampflex', 'Mat Lam Tam', 184);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (29, 'Konklux', 'Y-find', 'Zathin', 347);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (30, 'Ronstring', 'Alphazap', 'Namfix', 247);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (31, 'Veribet', 'Lotlux', 'Sub-Ex', 83);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (32, 'Y-Solowarm', 'Veribet', 'Veribet', 204);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (33, 'Asoka', 'Asoka', 'Keylex', 359);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (34, 'Daltfresh', 'Namfix', 'Matsoft', 281);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (35, 'Cardify', 'Lotstring', 'Fintone', 41);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (36, 'Bigtax', 'Tresom', 'Fintone', 154);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (37, 'Span', 'Sonsing', 'Bitwolf', 72);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (38, 'Cardguard', 'Konklux', 'Regrant', 61);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (39, 'Otcom', 'Kanlam', 'Veribet', 358);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (40, 'Cookley', 'Overhold', 'Biodex', 135);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (41, 'Y-find', 'Asoka', 'Wrapsafe', 291);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (42, 'Biodex', 'Domainer', 'Cardify', 89);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (43, 'Treeflex', 'Konklux', 'Lotstring', 241);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (44, 'Alpha', 'Cardify', 'Fintone', 338);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (45, 'Home Ing', 'Matsoft', 'Subin', 240);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (46, 'Cardguard', 'Zamit', 'Opela', 305);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (47, 'Bitwolf', 'Span', 'Aerified', 162);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (48, 'Y-Solowarm', 'It', 'Viva', 103);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (49, 'Transcof', 'Veribet', 'Bytecard', 256);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (50, 'Fixflex', 'Zaam-Dox', 'Wrapsafe', 171);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (51, 'Cardguard', 'Duobam', 'Tresom', 168);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (52, 'Cardguard', 'Latlux', 'Greenlam', 233);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (53, 'Daltfresh', 'Y-Solowarm', 'Voltsillam', 36);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (54, 'It', 'Ventosanzap', 'Transcof', 315);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (55, 'Zathin', 'Bitchip', 'Solarbreeze', 91);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (56, 'Voltsillam', 'Holdlamis', 'Daltfresh', 247);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (57, 'Y-Solowarm', 'Solarbreeze', 'Rank', 72);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (58, 'Solarbreeze', 'Bytecard', 'Flexidy', 204);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (59, 'Mat Lam Tam', 'Transcof', 'Sonsing', 233);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (60, 'Sonsing', 'Domainer', 'Bytecard', 216);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (61, 'It', 'Matsoft', 'Gembucket', 181);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (62, 'Latlux', 'Vagram', 'Fixflex', 257);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (63, 'Tin', 'Zoolab', 'It', 106);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (64, 'Konklux', 'Treeflex', 'Opela', 336);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (65, 'Prodder', 'Fintone', 'Cardguard', 65);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (66, 'Matsoft', 'Voyatouch', 'Cardguard', 196);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (67, 'Flexidy', 'Subin', 'Voltsillam', 268);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (68, 'Quo Lux', 'Latlux', 'Fintone', 77);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (69, 'Solarbreeze', 'Toughjoyfax', 'Tres-Zap', 74);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (70, 'Duobam', 'Zoolab', 'Domainer', 301);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (71, 'Voyatouch', 'Mat Lam Tam', 'Redhold', 192);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (72, 'Domainer', 'Sub-Ex', 'Biodex', 350);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (73, 'It', 'Fintone', 'Daltfresh', 225);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (74, 'Gembucket', 'Lotlux', 'Flexidy', 155);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (75, 'Vagram', 'Sonsing', 'Solarbreeze', 158);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (76, 'Span', 'Andalax', 'Lotlux', 103);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (77, 'Duobam', 'Cookley', 'Wrapsafe', 164);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (78, 'Zaam-Dox', 'Tin', 'Voltsillam', 183);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (79, 'Trippledex', 'Y-Solowarm', 'Stringtough', 340);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (80, 'Greenlam', 'Stringtough', 'Bitwolf', 244);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (81, 'Hatity', 'Subin', 'Zamit', 330);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (82, 'Toughjoyfax', 'Treeflex', 'Biodex', 118);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (83, 'Ronstring', 'Overhold', 'Fixflex', 61);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (84, 'Voltsillam', 'Y-find', 'Wrapsafe', 86);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (85, 'Cookley', 'Sub-Ex', 'Tin', 329);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (86, 'Pannier', 'Lotlux', 'Otcom', 144);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (87, 'Alphazap', 'Solarbreeze', 'Wrapsafe', 315);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (88, 'Matsoft', 'Namfix', 'Biodex', 73);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (89, 'Home Ing', 'Y-find', 'Matsoft', 134);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (90, 'Quo Lux', 'Bitchip', 'Ronstring', 311);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (91, 'Sub-Ex', 'Tresom', 'Vagram', 109);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (92, 'Hatity', 'Subin', 'Biodex', 65);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (93, 'Overhold', 'Stringtough', 'Holdlamis', 210);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (94, 'Rank', 'Span', 'Duobam', 179);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (95, 'Stringtough', 'Fix San', 'Bytecard', 159);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (96, 'Treeflex', 'Bytecard', 'Viva', 90);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (97, 'Fix San', 'Fintone', 'Span', 181);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (98, 'Home Ing', 'Bamity', 'Andalax', 318);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (99, 'Wrapsafe', 'Bitchip', 'Tresom', 297);
INSERT INTO playlist (id, arist_name, album_name, song, length) VALUES (100, 'Fix San', 'Veribet', 'Zathin', 256);
